(load "sequencer.scm")
(signal->wavfile (repeat 2 (dub (list (sequence 1 '((C 4 1)
                                                    (#f #f 1)
                                                    (C 4 1)
                                                    (#f #f 1)
                                                    (A# 3 1)
                                                    (#f #f 1)
                                                    (C 4 1)
                                                    (#f #f 3)
                                                    (G 3 1)
                                                    (#f #f 3)

                                                    (G 3 1)
                                                    (#f #f 1)
                                                    (C 4 1)
                                                    (#f #f 1)
                                                    (F 4 1)
                                                    (#f #f 1)
                                                    (E 4 1)
                                                    (#f #f 1)
                                                    (C 4 1)
                                                    (#f #f 1)
                                                    )
                                                245 sine-wave)
                                      1)
                                (list (drum 8 '(O #f #f #f) 245)
                                      1))))
