(load "sequencer.scm")
;; main riff from "Smoke on the Water", by Deep Purple
;; will take a while to generate, you might as well go grab some coffee
(signal->wavfile (dub (list (sequence 1 (list (chord 'D 2 1 'custom 0 5)
					      '(#f #f 1)
					      (chord 'D 2 1 'custom 3 8)
					      '(#f #f 1)
					      (chord 'D 2 2 'custom 5 10)
					      '(#f #f 1)
					      (chord 'D 2 1 'custom 0 5)
					      '(#f #f 1)
					      (chord 'D 2 1 'custom 3 8)
					      '(#f #f 1)
					      (chord 'D 2 1 'custom 6 11)
					      (chord 'D 2 2 'custom 5 10)
					      '(#f #f 2)
					      
					      (chord 'D 2 1 'custom 0 5)
					      '(#f #f 1)
					      (chord 'D 2 1 'custom 3 8)
					      '(#f #f 1)
					      (chord 'D 2 2 'custom 5 10)
					      '(#f #f 1)
					      (chord 'D 2 1 'custom 3 8)
					      '(#f #f 1)
					      (chord 'D 2 5 'custom 0 5))
				      112 sawtooth-wave)
			    1)
		      (list (drum 2 '(O #f X #f O #f X #f O #f X #f O O X X) 112)
			    1)))
